### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by suuankotanki** [charlesCXK/Depth2HHA-python#6]
Hello, I got an error when trying running your code.Here's the log:

(TF1.8) masaki@masaki-CP65R:~/Downloads/Depth2HHA-python-master$  cd /home/masaki/Downloads/Depth2HHA-python-master ; env /home/masaki/anaconda2/envs/TF1.8/bin/python /home/masaki/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher 40071 -- /home/masaki/Downloads/Depth2HHA-python-master/getHHA.py 
('max gray value: ', 3)
Traceback (most recent call last):
  File "/home/masaki/anaconda2/envs/TF1.8/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/masaki/anaconda2/envs/TF1.8/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/masaki/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/masaki/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/masaki/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/home/masaki/anaconda2/envs/TF1.8/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/home/masaki/anaconda2/envs/TF1.8/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/home/masaki/anaconda2/envs/TF1.8/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/masaki/Downloads/Depth2HHA-python-master/getHHA.py", line 71, in <module>
    hha = getHHA(camera_matrix, D, RD)
  File "/home/masaki/Downloads/Depth2HHA-python-master/getHHA.py", line 30, in getHHA
    pc, N, yDir, h, pcRot, NRot = processDepthImage(D * 100, missingMask, C)
  File "/home/masaki/Downloads/Depth2HHA-python-master/utils/rgbd_util.py", line 35, in processDepthImage
    1, C, np.ones(z.shape))
  File "/home/masaki/Downloads/Depth2HHA-python-master/utils/rgbd_util.py", line 112, in computeNormalsSquareSupport
    Z[ind] = np.nan
ValueError: cannot convert float NaN to integer

I edited the code in  getPointCloudFromZ():
z3=Z.astype(np.float) 
But the final image is not the same as your demo image. Can you tell me how to deal with it?
![hha](https://user-images.githubusercontent.com/57520980/81943860-8018ea80-962e-11ea-8e2b-464502b6dea5.png)

**Comment by charlesCXK** [comment]
Hi, what's your raw depth map look like? Besides, is it in 'meters'?

**Comment by suuankotanki** [comment]
Hello,I just runned the default demo.py to check whether the code works or not, I didn't use my own raw depth map,just the default 0.png under the demo folder. The result is Value error.

**Comment by charlesCXK** [comment]
I run the code again, and it works. I get the following output:
`max gray value:  3.6156`
I notice that your output is `('max gray value: ', 3)`, did you modify the code?

By the way, I run this code with Python3, and I am not sure whether it works on Python2. Maybe this is the point.

**Comment by suuankotanki** [comment]
Thank you very much, The problem was exactly on python2.7, I switched to python3 and the problem was fixed.Thanks again for your excellent code ! :)
